### PR TITLE
Upgrade to 1.2.0 release

### PR DESCRIPTION
**Pull request by flub**

### CODE REVIEW

**Review by nicoddemus — APPROVED** [review]

**Comment by nicoddemus** [comment]
@flub the failures on Travis indicate that we probably need to re-render the feedstock, there's instructions on how to do it [here](https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock). I can do it later tonight if you don't have conda installed or don't want to install it.

**Comment by nicoddemus** [comment]
Re-rendered. 😁

**Comment by nicoddemus** [comment]
Oh my Travis is taking forever 😓

**Comment by ocefpaf** [comment]
Check their status online. It seems Travis won't be back soon.

**Comment by nicoddemus** [comment]
Oh yeah, thanks @ocefpaf. It seems it has resumed and is now working through the backlog:

https://www.traviscistatus.com/:

> Public repos are back to full capacity. We are working through the accumulated backlog.

**Comment by flub** [comment]
Oh, thanks for the re-rendering pointer.  I didn't find that.  Would be nice if PRs for this where done automatically...

And I've got many conda root environments in all sorts of variations... ;-)

**Comment by nicoddemus** [comment]
>  Would be nice if PRs for this where done automatically...

There's a robot that occasionally opens PRs re-rendering feedstocks, but I guess it takes awhile to catch up.

> And I've got many conda root environments in all sorts of variations... ;-)

😁

**Pull request merged**
